[theme]
primaryColor="#FF6B9D"
backgroundColor="#FFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[client]
showErrorDetails=true
toolbarMode="minimal"

[server]
port=5000
headless=true
runOnSave=true
maxUploadSize=1000

[logger]
level="warning"
